In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [3]:
# will check with type function
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

while printing type of the data structure we can infer that 

list_ : list data structure

array_list : array in numpy

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
# data type of every element of variables list_ 
for i in list_:
    print(i,type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [10]:
# data type of every element of variables array_list
for i in array_list:
    print(i, type(i))

1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [11]:
array_list = np.array(object = list_, dtype = int)

In [12]:
list_

['1', '2', '3', '4', '5']

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
# data type of every element of variables list_ 
for i in list_:
    print(i,type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [15]:
# data type of every element of variables array_list
for i in array_list:
    print(i, type(i))

1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


Data type:

list_ : str

arry_list : int

In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [17]:
num_array.shape

(2, 3)

In [18]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [22]:
arr5 = np.zeros((3,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
arr6 = np.eye(5)
arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])